name: abd_libraries

services:
  library_user:
    container_name: lus
    build:
      context: ./library_user_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./library_user_service:/usr/src/app
    ports:
      - "8081:3000"
    depends_on:
      - redis
      - postgres
    stop_grace_period: 1s # stop bun dev immediately

  book_service:
    container_name: bos
    build:
      context: ./book_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./book_service:/usr/src/app
    ports:
      - "8082:3000"
    depends_on:
      - redis
      - postgres

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    ports:
      - "6379:6379"

  postgres:
    container_name: postgres
    build:
      context: ./postgres
      dockerfile: Dockerfile.dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local
