name: abd_libraries

services:
  library_user:
    container_name: lus
    build:
      context: ./library_user_service
      dockerfile: Dockerfile.dev
    volumes:
      - ./library_user_service:/usr/src/app
    ports:
      - "8081:3000"
    depends_on:
      - redis

  redis:
    container_name: redis
    build:
      context: ./redis
      dockerfile: Dockerfile.dev
    ports:
      - "6379:6379"
