FROM oven/bun:1 as base
WORKDIR /usr/src/app

FROM base as dev
COPY ./package.json ./package.json
COPY ./bun.lockb ./bun.lockb
RUN bun install --frozen-lockfile

USER bun
EXPOSE 3000/tcp
CMD [ "bun", "dev" ]