// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Bibliography struct {
	ID         string       `json:"id"`
	Name       string       `json:"name"`
	Isbn       *string      `json:"ISBN,omitempty"`
	BookStocks []*BookStock `json:"bookStocks"`
}

type BookStock struct {
	ID             string        `json:"id"`
	Detail         *string       `json:"detail,omitempty"`
	BibliographyID string        `json:"bibliographyId"`
	Bibliography   *Bibliography `json:"bibliography"`
}

type CreateBibliographyInput struct {
	Name string  `json:"name"`
	Isbn *string `json:"ISBN,omitempty"`
}

type CreateBookStockInput struct {
	Detail         *string `json:"detail,omitempty"`
	BibliographyID string  `json:"bibliographyId"`
}

type Mutation struct {
}

type Query struct {
}
