FROM postgres:16.2 as base

# RUN localedef -i ja_JP -c -f UTF-8 -A /usr/share/locale/locale.alias ja_JP.UTF-8
# ENV LANG ja_JP.UTF-8
ENV TZ=Asia/Tokyo

ENV POSTGRES_USER=posadmin
ENV POSTGRES_PASSWORD=pospass

COPY ./docker-entrypoint-initdb.d /docker-entrypoint-initdb.d

EXPOSE 5432/tcp
